# Generated by Django 4.2.3 on 2023-08-01 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='lottery_539',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drawdate', models.DateField()),
                ('num_1', models.SmallIntegerField()),
                ('num_2', models.SmallIntegerField()),
                ('num_3', models.SmallIntegerField()),
                ('num_4', models.SmallIntegerField()),
                ('num_5', models.SmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
